version: "3.7"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3001:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
